import type { Metadata } from "next";
// import "./globals.css";
import { NavBar } from "@/components/nav-bar";


// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
        <div className="pt-10 px-5">
          {children}
        </div>
      </>
  );
}
